### ISSUE TITLE
General mess

### ISSUE THREAD

**Issue by jaimejim** [ewaldc/spotify-ripper#1]
This seems to be the only still active fork of spotify ripper and it currently it is a bit of a mess. 
I'd redo the README and simplify the installation to the basics, dockerizing everything if possible.

**Comment by ewaldc** [comment]
Yes, it is...   I have made no attempt to clean it up or throw out  sections of the code which I rewrote to use the web services API.  None of the versions I tried worked for me, so I created a fork from the version that seemed closest to a working version and fixed the parts that seemed wrong to me.
So despite being a bit of a mess, it is working well. I added a few options e.g. to just update the album art.  
If I have a little time I will create a simpler readme. Docker seems easier than simplifying install.

**Comment by jaimejim** [comment]
It does work indeed, sorry for the doubt, it took me a while but now it is fixed for me.
